export const GET_ALL_DATA_REQUEST="GET_ALL_DATA_REQUEST"
export const GET_ALL_DATA_SUCESS="GET_ALL_DATA_SUCESS"
export const GET_ALL_DATA_FAILURE="GET_ALL_DATA_FAILURE"

export const SORT_DATA="SORT_DATA"
export const FILTER_DATA="FILTER_DATA"
export const PAGINATED_DATA="PAGINATED_DATA"

